// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyb_xNTAVQFvfaP5WkBI6p6x2d2UZ3lHg',
    appId: '1:144558859080:web:f449193a4eff32d1c6097d',
    messagingSenderId: '144558859080',
    projectId: 'quiz-app-leo',
    authDomain: 'quiz-app-leo.firebaseapp.com',
    storageBucket: 'quiz-app-leo.firebasestorage.app',
    measurementId: 'G-RZW4P009W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64qGOsPtMft_IpdV3aIbJjl7oaOF51u4',
    appId: '1:144558859080:android:837200b31e571a44c6097d',
    messagingSenderId: '144558859080',
    projectId: 'quiz-app-leo',
    storageBucket: 'quiz-app-leo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJpXdhODTsbO6mxRWQtBbXXwXUPiCRio',
    appId: '1:144558859080:ios:3e9fcf0cd33e95d8c6097d',
    messagingSenderId: '144558859080',
    projectId: 'quiz-app-leo',
    storageBucket: 'quiz-app-leo.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJpXdhODTsbO6mxRWQtBbXXwXUPiCRio',
    appId: '1:144558859080:ios:3e9fcf0cd33e95d8c6097d',
    messagingSenderId: '144558859080',
    projectId: 'quiz-app-leo',
    storageBucket: 'quiz-app-leo.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyb_xNTAVQFvfaP5WkBI6p6x2d2UZ3lHg',
    appId: '1:144558859080:web:c5fa11c7ffe130edc6097d',
    messagingSenderId: '144558859080',
    projectId: 'quiz-app-leo',
    authDomain: 'quiz-app-leo.firebaseapp.com',
    storageBucket: 'quiz-app-leo.firebasestorage.app',
    measurementId: 'G-5QT7CB93C4',
  );
}
